language: python

os:
  - linux

services:
  - couchdb

python:
  - "2.6"
  - "2.7"

install:
  - pip install -r hints_provider/requirements.txt
  - pip install -r stats_updater/requirements.txt
  - pip install -r flask_public_server/requirements.txt
  - pip install -r stats_analyser/requirements.txt
  - pip install -r test_management/requirements.txt
  - pip install coverage

before_script:
  - curl -X PUT localhost:5984/progress
  
script: 
  - coverage run -m pytest -v
  - coverage report
