language: python

os:
  - linux

services:
  - couchdb
  - mysql

python:
  - "2.6"
  - "2.7"

before_install:
  - mysql -e 'CREATE DATABASE oauth;'
  - curl -X PUT localhost:5984/progress

install:
  - pip install -r hints_provider/requirements.txt
  - pip install -r stats_updater/requirements.txt
  - pip install -r flask_public_server/requirements.txt
  - pip install -r stats_analyser/requirements.txt
  - pip install -r test_management/requirements.txt
  - pip install coverage

before_script:
  - touch flask_public_server/config.cfg
  - FLASK_CONFIGURATION='testing' FLASK_APP=flask_public_server/flask_public_server/flask_public_server.py flask initdb
  
script: 
  - FLASK_CONFIGURATION='testing' coverage run -m pytest -v
  - coverage report
