language: python

os:
  - linux

services:
  - couchdb
  - mysql

python:
  - "2.6"
  - "2.7"

env:
  - FLASK_CONFIGURATION=testing

before_install:
  - mysql -e 'CREATE DATABASE oauth;'

install:
  - pip install -r hints_provider/requirements.txt
  - pip install -r stats_updater/requirements.txt
  - pip install -r flask_public_server/requirements.txt
  - pip install -r stats_analyser/requirements.txt
  - pip install -r test_management/requirements.txt
  - pip install coverage

before_script:
  - curl -X PUT localhost:5984/progress
  - touch flask_public_server/config.cfg
  - FLASK_APP=flask_public_server/flask_public_server/flask_public_server.py flask initdb
  - FLASK_APP=flask_public_server/flask_public_server/flask_public_server.py flask seeddb
  - FLASK_APP=stats_updater/stats_updater/stats_updater.py flask initdb
  
script: 
  - make launch
  - coverage run -m pytest -v
  - coverage report

after_script:
  - make shutdown
