language: python

os:
  - linux

services:
  - mongod

python:
  - "2.6"
  - "2.7"
  - "3.6"

install:
  - pip install -r hints_provider/requirements.txt
  - pip install -r stats_updater/requirements.txt
  - pip install -r flask_public_server/requirements.txt
  
script: 
  - pytest -v