SITE_SERVER_HOST = '51.140.38.242'
SITE_SERVER_PORT = 5000

EXTERNAL_SERVER_HOST = 'localhost'
EXTERNAL_SERVER_PORT = 5001

SITE_SERVER_URL = "http://%s:%s" % (SITE_SERVER_HOST, SITE_SERVER_PORT)
EXTERNAL_SERVER_URL = "http://%s:%s/hints" % (EXTERNAL_SERVER_HOST, EXTERNAL_SERVER_PORT)


SAMPLE_DATA_MAX = 5000

